spring:
  application:
    name: finance-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080